Add hooks for logging events, guards, actions, and state transitions
korken89/smlang-rs pull request #68
Opened 2024-04-14 02:39 UTC by mhammerly

Boost.SML allows a user to provide a type which defines `log_process_event()`, `log_guard()`, `log_action()`, and `log_state_change()` functions that it'll call at the appropriate times ([docs](https://boost-ext.github.io/sml/examples.html#logging)). This PR builds something comparable for `smlang-rs` and exhibits its usage in `examples/state_machine_logger.rs`.

It's not an exact match with Boost.SML's:
- Boost.SML passes the event to `log_guard()` and `log_action()`
- Boost.SML passes the originating state to `log_state_transition()`
- Boost.SML does not pass the current state to `log_process_event()`

The deviations in this PR were to work around partial moves of state/event data. For example, partially moving data from the originating state into an action can be a prerequisite for creating the destination state. There wasn't an obvious way for `log_state_change()` to simultaneously access both. The example shows how this design can still be workable. It scratches my itch, anyway.

2024-04-14 02:51 UTC, mhammerly commented
also do you have plans to push a release sometime soon? there looks to be some good stuff in the commit history since the last release at the end of 2022

2024-04-15 08:40 UTC, ryan-summers commented
I'd be happy to publish a release if desired :) It indeed has been quite a while.

2024-04-15 08:45 UTC, ryan-summers requested changes
Can you please add a CHANGELOG.md entry to note this addition?

2024-04-15 08:45 UTC, ryan-summers commented on examples/state_machine_logger.rs
> +    [StateMachineLogger]    Transitioning to State3
This is a wonderful addition, thanks for taking the time to implement this. I can see this as being quite useful for users! :)

2024-04-15 17:16 UTC, mhammerly commented
changelog entry added!

re a release, including from git is fine for my project and i would feel bad nudging for a big release if it resulted in a bunch of new issues you don't have bandwidth for lol. but i imagine users who aren't watching the github would be pleased to see these unreleased features whenever you find a good time

naturally if there are any problems related to this please @ me and i'll try to help

2024-04-15 17:49 UTC, ryan-summers commented
I'll merge and and release this tomorrow morning when I'm back in the office. Thanks!

2024-04-16 08:37 UTC, ryan-summers approved these changes

2024-04-16 08:37 UTC, merged